blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://pkg.go.dev/github.com/b58uuid/b58uuid-go
    about: View the package documentation on pkg.go.dev
  - name: Discussions
    url: https://github.com/b58uuid/b58uuid-go/discussions
    about: Ask questions and discuss ideas with the community
